/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramaPrincipal;

import Recursos.Conexion;
import Recursos.Usuario;
import Recursos.EncriptaPass;
import Recursos.Utilidades;
import java.awt.Color;
import java.awt.Cursor;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;

/**
 *
 * @author admin
 */
public class Login extends javax.swing.JFrame {
    
    //Codigo para generar la base de datos
    private static String CODIGO_BASE;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        btnIniciar = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        lblCred = new javax.swing.JLabel();
        lblCrearBase = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(Utilidades.ponerIcono());
        setResizable(false);

        lblUsuario.setText("Email: ");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("Iniciar Sesión");

        lblPass.setText("Contraseña:");

        btnIniciar.setText("Iniciar Sesión");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo.jpg"))); // NOI18N

        lblCred.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblCred.setText("Credenciales del servidor");
        lblCred.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCredMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCredMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCredMouseExited(evt);
            }
        });

        lblCrearBase.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblCrearBase.setText("Crear base de datos");
        lblCrearBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrearBaseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCrearBaseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCrearBaseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblImage)
                            .addComponent(lblTitulo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPass)
                    .addComponent(lblUsuario))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblCrearBase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCred, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass))
                .addGap(36, 36, 36)
                .addComponent(btnIniciar)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCred)
                    .addComponent(lblCrearBase))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        //Boton de inicio de sesion
        if(!(txtUsuario.getText().equals("") || String.valueOf(txtPass.getPassword()).equals(""))){
            Usuario user = Conexion.recogeUsuario(txtUsuario.getText());
            if(!(user == null)){
                //Si el user existe compruebo si su contraseña es la correcta
                if(user.getPass().equals(EncriptaPass.StringToHash(String.valueOf(txtPass.getPassword())))){
                    //Abro el frame del menu principal
                    MenuPrincipal menu = new MenuPrincipal(user);
                    menu.setVisible(true);
                    //Quito esta ventana
                    this.dispose();
                }else{
                    mensajeError("La contraseña no es correcta");
                }
            }
        }else{
            mensajeError("Por favor, rellene los datos de inicio de sesión");
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void lblCredMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCredMouseEntered
        //Cuando paso por encima, cambio el color a azul, cambio el icono del cursos, para que sea como un enlace
        lblCred.setForeground(Color.BLUE);
        lblCred.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblCredMouseEntered

    private void lblCredMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCredMouseExited
        //Cuando salgo, cambio el color al que tiene por defecto
        lblCred.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblCredMouseExited

    private void lblCredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCredMouseClicked
        //Abro una ventana en la cual pregunto las credenciales del servidor
        CredencialesServidor cred = new CredencialesServidor();
        cred.setVisible(true);
    }//GEN-LAST:event_lblCredMouseClicked

    private void lblCrearBaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearBaseMouseClicked
        try {
            mensajePass();
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblCrearBaseMouseClicked

    private void lblCrearBaseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearBaseMouseEntered
        //Cambio el color del label de crear base
        lblCrearBase.setForeground(Color.BLUE);
        lblCrearBase.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblCrearBaseMouseEntered

    private void lblCrearBaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearBaseMouseExited
        //Pongo el color del label de crear base al que tenia por defecto
        lblCrearBase.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblCrearBaseMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    private void mensajeError(String error) {
        JOptionPane.showMessageDialog(null,error,"Error al iniciar sesión",JOptionPane.ERROR_MESSAGE);
    }
    
    private void mensajePass() throws IOException{
        //Codigo que se genera y se guarda en un fichero
        CODIGO_BASE = Utilidades.generaCodigo();
        Utilidades.generaFichero(EncriptaPass.AESEncriptar(CODIGO_BASE));
        JOptionPane.showMessageDialog(null,"Archivo con el codigo para desencriptar creado","Informacion",JOptionPane.INFORMATION_MESSAGE);
        
        JPanel panel = new JPanel();
        JLabel label = new JLabel("Introduzca el codigo");
        JPasswordField pass = new JPasswordField(10);
        panel.add(label);
        panel.add(pass);
        String[] opxiones = new String[]{"OK", "Cancelar"};
        int option = JOptionPane.showOptionDialog(null, panel, "Confirmar",
                                 JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                                 null, opxiones, opxiones[1]);
        
        // Si pulsa OK
        if(option == 0){
            String password = String.valueOf(pass.getPassword());
            if(!(password.equals(""))){
                if(password.equals(CODIGO_BASE)){
                    Conexion.crearBase();
                }else{
                    JOptionPane.showMessageDialog(null,"Codigo introducido erroneo","Error",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null,"No deje el campo vacio","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel lblCrearBase;
    private javax.swing.JLabel lblCred;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}